// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/pbjs/annotations.proto

package pbjs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_pbjs_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbjs_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_pbjs_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

var file_proto_pbjs_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Message)(nil),
		Field:         15895583,
		Name:          "pbjs.message",
		Tag:           "bytes,15895583,opt,name=message",
		Filename:      "proto/pbjs/annotations.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional pbjs.Message message = 15895583;
	E_Message = &file_proto_pbjs_annotations_proto_extTypes[0]
)

var File_proto_pbjs_annotations_proto protoreflect.FileDescriptor

const file_proto_pbjs_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/pbjs/annotations.proto\x12\x04pbjs\x1a google/protobuf/descriptor.proto\"#\n" +
	"\aMessage\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject:K\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\x9f\x98\xca\a \x01(\v2\r.pbjs.MessageR\amessageB)Z'github.com/stevecallear/pbjs/proto/pbjsb\x06proto3"

var (
	file_proto_pbjs_annotations_proto_rawDescOnce sync.Once
	file_proto_pbjs_annotations_proto_rawDescData []byte
)

func file_proto_pbjs_annotations_proto_rawDescGZIP() []byte {
	file_proto_pbjs_annotations_proto_rawDescOnce.Do(func() {
		file_proto_pbjs_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pbjs_annotations_proto_rawDesc), len(file_proto_pbjs_annotations_proto_rawDesc)))
	})
	return file_proto_pbjs_annotations_proto_rawDescData
}

var file_proto_pbjs_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_pbjs_annotations_proto_goTypes = []any{
	(*Message)(nil),                     // 0: pbjs.Message
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_proto_pbjs_annotations_proto_depIdxs = []int32{
	1, // 0: pbjs.message:extendee -> google.protobuf.MessageOptions
	0, // 1: pbjs.message:type_name -> pbjs.Message
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pbjs_annotations_proto_init() }
func file_proto_pbjs_annotations_proto_init() {
	if File_proto_pbjs_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pbjs_annotations_proto_rawDesc), len(file_proto_pbjs_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proto_pbjs_annotations_proto_goTypes,
		DependencyIndexes: file_proto_pbjs_annotations_proto_depIdxs,
		MessageInfos:      file_proto_pbjs_annotations_proto_msgTypes,
		ExtensionInfos:    file_proto_pbjs_annotations_proto_extTypes,
	}.Build()
	File_proto_pbjs_annotations_proto = out.File
	file_proto_pbjs_annotations_proto_goTypes = nil
	file_proto_pbjs_annotations_proto_depIdxs = nil
}
