// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/proto/testpb/testpb.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchOrderCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchOrderCommand) Reset() {
	*x = DispatchOrderCommand{}
	mi := &file_internal_proto_testpb_testpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchOrderCommand) ProtoMessage() {}

func (x *DispatchOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_testpb_testpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchOrderCommand.ProtoReflect.Descriptor instead.
func (*DispatchOrderCommand) Descriptor() ([]byte, []int) {
	return file_internal_proto_testpb_testpb_proto_rawDescGZIP(), []int{0}
}

type OrderDispatchedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDispatchedEvent) Reset() {
	*x = OrderDispatchedEvent{}
	mi := &file_internal_proto_testpb_testpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDispatchedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDispatchedEvent) ProtoMessage() {}

func (x *OrderDispatchedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_testpb_testpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDispatchedEvent.ProtoReflect.Descriptor instead.
func (*OrderDispatchedEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_testpb_testpb_proto_rawDescGZIP(), []int{1}
}

func (x *OrderDispatchedEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrderFulfilledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFulfilledEvent) Reset() {
	*x = OrderFulfilledEvent{}
	mi := &file_internal_proto_testpb_testpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFulfilledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFulfilledEvent) ProtoMessage() {}

func (x *OrderFulfilledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_testpb_testpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFulfilledEvent.ProtoReflect.Descriptor instead.
func (*OrderFulfilledEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_testpb_testpb_proto_rawDescGZIP(), []int{2}
}

func (x *OrderFulfilledEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_internal_proto_testpb_testpb_proto protoreflect.FileDescriptor

const file_internal_proto_testpb_testpb_proto_rawDesc = "" +
	"\n" +
	"\"internal/proto/testpb/testpb.proto\x12\x06testpb\"\x16\n" +
	"\x14DispatchOrderCommand\"&\n" +
	"\x14OrderDispatchedEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13OrderFulfilledEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB4Z2github.com/stevecallear/pbjs/internal/proto/testpbb\x06proto3"

var (
	file_internal_proto_testpb_testpb_proto_rawDescOnce sync.Once
	file_internal_proto_testpb_testpb_proto_rawDescData []byte
)

func file_internal_proto_testpb_testpb_proto_rawDescGZIP() []byte {
	file_internal_proto_testpb_testpb_proto_rawDescOnce.Do(func() {
		file_internal_proto_testpb_testpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_testpb_testpb_proto_rawDesc), len(file_internal_proto_testpb_testpb_proto_rawDesc)))
	})
	return file_internal_proto_testpb_testpb_proto_rawDescData
}

var file_internal_proto_testpb_testpb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_testpb_testpb_proto_goTypes = []any{
	(*DispatchOrderCommand)(nil), // 0: testpb.DispatchOrderCommand
	(*OrderDispatchedEvent)(nil), // 1: testpb.OrderDispatchedEvent
	(*OrderFulfilledEvent)(nil),  // 2: testpb.OrderFulfilledEvent
}
var file_internal_proto_testpb_testpb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_testpb_testpb_proto_init() }
func file_internal_proto_testpb_testpb_proto_init() {
	if File_internal_proto_testpb_testpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_testpb_testpb_proto_rawDesc), len(file_internal_proto_testpb_testpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_testpb_testpb_proto_goTypes,
		DependencyIndexes: file_internal_proto_testpb_testpb_proto_depIdxs,
		MessageInfos:      file_internal_proto_testpb_testpb_proto_msgTypes,
	}.Build()
	File_internal_proto_testpb_testpb_proto = out.File
	file_internal_proto_testpb_testpb_proto_goTypes = nil
	file_internal_proto_testpb_testpb_proto_depIdxs = nil
}
