// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/proto/testpb/testpb.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageA) Reset() {
	*x = MessageA{}
	mi := &file_internal_proto_testpb_testpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageA) ProtoMessage() {}

func (x *MessageA) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_testpb_testpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageA.ProtoReflect.Descriptor instead.
func (*MessageA) Descriptor() ([]byte, []int) {
	return file_internal_proto_testpb_testpb_proto_rawDescGZIP(), []int{0}
}

func (x *MessageA) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MessageB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageB) Reset() {
	*x = MessageB{}
	mi := &file_internal_proto_testpb_testpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageB) ProtoMessage() {}

func (x *MessageB) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_testpb_testpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageB.ProtoReflect.Descriptor instead.
func (*MessageB) Descriptor() ([]byte, []int) {
	return file_internal_proto_testpb_testpb_proto_rawDescGZIP(), []int{1}
}

func (x *MessageB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageB) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_internal_proto_testpb_testpb_proto protoreflect.FileDescriptor

const file_internal_proto_testpb_testpb_proto_rawDesc = "" +
	"\n" +
	"\"internal/proto/testpb/testpb.proto\x12\x06testpb\" \n" +
	"\bMessageA\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"4\n" +
	"\bMessageB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversionB4Z2github.com/stevecallear/pbjs/internal/proto/testpbb\x06proto3"

var (
	file_internal_proto_testpb_testpb_proto_rawDescOnce sync.Once
	file_internal_proto_testpb_testpb_proto_rawDescData []byte
)

func file_internal_proto_testpb_testpb_proto_rawDescGZIP() []byte {
	file_internal_proto_testpb_testpb_proto_rawDescOnce.Do(func() {
		file_internal_proto_testpb_testpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_testpb_testpb_proto_rawDesc), len(file_internal_proto_testpb_testpb_proto_rawDesc)))
	})
	return file_internal_proto_testpb_testpb_proto_rawDescData
}

var file_internal_proto_testpb_testpb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_testpb_testpb_proto_goTypes = []any{
	(*MessageA)(nil), // 0: testpb.MessageA
	(*MessageB)(nil), // 1: testpb.MessageB
}
var file_internal_proto_testpb_testpb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_testpb_testpb_proto_init() }
func file_internal_proto_testpb_testpb_proto_init() {
	if File_internal_proto_testpb_testpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_testpb_testpb_proto_rawDesc), len(file_internal_proto_testpb_testpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_testpb_testpb_proto_goTypes,
		DependencyIndexes: file_internal_proto_testpb_testpb_proto_depIdxs,
		MessageInfos:      file_internal_proto_testpb_testpb_proto_msgTypes,
	}.Build()
	File_internal_proto_testpb_testpb_proto = out.File
	file_internal_proto_testpb_testpb_proto_goTypes = nil
	file_internal_proto_testpb_testpb_proto_depIdxs = nil
}
