name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:alpine
        ports:
          - 4222:4222
        options: --name nats
    strategy:
      fail-fast: false
      matrix:
        go: [1.24, 1.25]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"
      - name: Start JetStream
        run: |
          chmod a+x ${{ github.workspace }}/.github/workflows/entrypoint.sh
          docker cp ${{ github.workspace }}/.github/workflows/entrypoint.sh nats:/usr/local/bin/docker-entrypoint.sh
          docker restart nats
      - name: Build
        run: |
          go vet .
          NATS_URL=nats:4222 go test . -race -coverprofile=coverage.txt -covermode=atomic
      - name: Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}